name: sharedcrowd-platform
services:
- name: web
  source_dir: /
  github:
    repo: Heisenberger448/EventsHUB
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: |
    npm ci
    npx prisma generate
    npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  health_check:
    http_path: /api/health
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXTAUTH_URL
    value: ${APP_URL}
  - key: NEXTAUTH_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET

databases:
- name: sharedcrowd-db
  engine: PG
  version: "15"
  size: basic-xs